#!/usr/bin/env node
// golden-node.mjs — the headless SimCore golden-hash run (03 §12).
//
// This is the `node-golden` job of `.github/workflows/determinism-matrix.yml`,
// and it is the whole point of P2: the same corpus, stepped the same number of
// times, must produce byte-identical state hashes on linux-x64 and macos-arm64,
// under both Node LTS lines. That equality *is* the U9 answer for the Node half
// of the matrix; the browser triple (P2c) then has to match these same numbers.
//
// What gets compared is not just the final hash. Every 60th step is a
// checkpoint, so a divergence reports the *step it started at* rather than only
// that the run ended somewhere else — with 3 600 steps and one number at the
// end, "the hash differs" is nearly uninvestigable.
//
// The analytics report travels with the goldens for the same reason it travels
// with a leaderboard submission (D17): `efficiencyScore` and `longestChain` are
// engineVersion-scoped, so a change to a metric definition that left the physics
// untouched would otherwise pass a hash-only gate and silently re-rank every
// board.
//
// Zero dependencies. Run:
//   pnpm run golden           compare against the committed goldens
//   pnpm run golden:update    rewrite them (a reviewed act — see corpus.json)

import { readFileSync, writeFileSync } from 'node:fs';
import { compareKey, compareScene } from './golden-compare.mjs';
import { ROOT, readRepoJson, repoPath } from './repo.mjs';

/** Header written into the golden file, so a reader knows what they are looking at. */
const GOLDEN_COMMENT = [
  'GENERATED by tools/golden-node.mjs --update. Do not hand-edit.',
  'These are the 03 §12 golden hashes: the same numbers every platform in',
  'determinism-matrix.yml must reproduce. A diff here is either a deliberate',
  'engine change (which must come with an engineVersion bump — 03 §2) or a',
  'determinism incident. It is never a routine update.',
  'The run plan that produced them is packages/engine/goldens/corpus.json.',
];

const UPDATE = process.argv.includes('--update');
const JSON_OUT = process.argv.includes('--json');

const enginePath = repoPath('packages/engine/dist/src/index.js');
const engine = await import(new URL(`file://${enginePath}`).href);
const { createSimCore, PHYSICS_PACKAGE } = engine;

const corpus = readRepoJson('packages/engine/goldens/corpus.json');
const GOLDEN_PATH = repoPath('packages/engine/goldens/state.golden.json');
const enginePkg = readRepoJson('packages/engine/package.json');

/** The 10 §6 key: goldens are only comparable within one engine build. */
const key = {
  engineVersion: enginePkg.version,
  physicsBuild: `${PHYSICS_PACKAGE}@${enginePkg.dependencies[PHYSICS_PACKAGE]}`,
};

function loadScene(name) {
  return JSON.parse(readFileSync(repoPath(`packages/engine/goldens/scenes/${name}.json`), 'utf8'));
}

/**
 * Run one corpus scene, sampling the state hash every `checkpointEvery` steps.
 *
 * A scene that reaches a §9.2 finish condition stops there — `advance` returns
 * short — and the run records the step it stopped at. That step is part of the
 * determinism surface too: two platforms that agreed on every hash but
 * disagreed about when a machine went quiet would not be deterministic.
 */
async function runScene(name) {
  const doc = loadScene(name);
  const sim = await createSimCore();
  const load = sim.load(doc);
  const checkpoints = [];
  const started = process.hrtime.bigint();
  while (sim.stepIndex < corpus.steps && sim.finished === null) {
    const want = Math.min(corpus.checkpointEvery, corpus.steps - sim.stepIndex);
    sim.advance(want);
    checkpoints.push(`${sim.stepIndex}:${sim.hash()}`);
  }
  const ms = Number(process.hrtime.bigint() - started) / 1e6;
  const report = sim.report();
  return {
    result: {
      bodyCount: load.bodyCount,
      warnings: load.warnings.map((w) => w.code),
      endStep: sim.stepIndex,
      finishReason: sim.finished,
      checkpoints,
      analytics: {
        durationS: report.durationS,
        objectsActivated: report.objectsActivated,
        activatableCount: report.activatableCount,
        chainReactions: report.chainReactions,
        longestChain: report.longestChain,
        success: report.success,
        removedCount: report.removedCount,
        efficiencyScore: report.efficiencyScore,
        finalHash: report.finalHash,
      },
    },
    ms,
  };
}

const measured = {};
const timings = {};
for (const entry of corpus.scenes) {
  const { result, ms } = await runScene(entry.name);
  measured[entry.name] = result;
  timings[entry.name] = ms;
}

if (UPDATE) {
  const out = { _comment: GOLDEN_COMMENT, key, steps: corpus.steps, checkpointEvery: corpus.checkpointEvery, scenes: measured };
  writeFileSync(GOLDEN_PATH, `${JSON.stringify(out, null, 2)}\n`);
  console.log(`wrote ${GOLDEN_PATH.slice(ROOT.length + 1)} for ${key.engineVersion} / ${key.physicsBuild}`);
  for (const entry of corpus.scenes) {
    const r = measured[entry.name];
    console.log(`  ${entry.name.padEnd(20)} ${String(r.bodyCount).padStart(5)} bodies  ${String(r.endStep).padStart(5)} steps  ${r.analytics.finalHash}  (${timings[entry.name].toFixed(0)} ms)`);
  }
  process.exit(0);
}

const golden = readRepoJson('packages/engine/goldens/state.golden.json');
let fails = 0;
const A = (cond, msg) => {
  console.log(`  ${cond ? 'ok  ' : 'FAIL'} ${msg}`);
  if (!cond) fails++;
};

console.log(`golden-node — ${key.engineVersion} on ${process.platform}-${process.arch}, ${process.version}`);
console.log(`  physics build: ${key.physicsBuild}`);
console.log('');

for (const finding of compareKey(key, corpus, golden)) A(finding.ok, finding.msg);

for (const entry of corpus.scenes) {
  const got = measured[entry.name];
  console.log(`\n${entry.name} — ${entry.why}`);
  for (const finding of compareScene(got, golden.scenes[entry.name])) A(finding.ok, finding.msg);
  console.log(`  --   ${timings[entry.name].toFixed(0)} ms for ${got.endStep} steps over ${got.bodyCount} bodies`);
}

if (JSON_OUT) console.log(`\n${JSON.stringify({ key, scenes: measured }, null, 2)}`);

console.log(`\n${'-'.repeat(40)}`);
console.log(`failures: ${fails}`);
console.log(`golden-node: ${fails === 0 ? 'GREEN' : 'RED'}`);
process.exitCode = fails === 0 ? 0 : 1;
